version: "3.8"

services:
  backend:
    build: ./backend
    container_name: secure_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./users.db
